### PR TITLE
Add tagify.js to update labels feature

### PR DESCRIPTION
**Pull request by polrodoreda**

### CODE REVIEW

**Comment by polrodoreda** [comment]
I need to fix a bug in the home page, don't merge it

**Comment by polrodoreda** [comment]
@pasqualguerrero tens feina!!! :wink:

**Comment by pasqualguerrero** [comment]
omfg :metal: i'll take a look :smile:

**Comment by pasqualguerrero** [comment]
Looks really good to me, if @sabueso agrees i'll merge it asap :metal: 

A really good work @polrodoreda  :tada:

**Review by pasqualguerrero — APPROVED** [review]

**Pull request merged**
