### PR TITLE
Architecture refactor

### PR DESCRIPTION
**Pull request by ma0c**
Hi there sabueso,

Has been a long time since last time, more than a year, and although I haven't been much active  with ticketator, I still have the project on my mind. Recently at work we need to deploy a simple ticket system and of course I want to go with Ticketator. But before go any further I like to make my honest contribution.

I just take the freedom and refactor the whole project to a more standard way. The biggest changes are:

* Separate Forms from Model in a new file `forms.py`
* Group view files in a `view` package
* Manage Urls inside `core` package instead main `ticketator/urls.py` file
* Move templates from root folder to `core/templates/core`

Another minor changes are remove auth_views, instead use `auth_views.logout_then_login` (this package will be deprecated in favor for auth CBV introduces in Django 1.11, but for the django 1.10 structure is ok) Remove circular imports with `core/logs.py` and make more readable models and forms definitions leaving a single attribute per line.

I made a mistake, because instead of form from `devel` branch, made a fork form `master`, and just after a big refactoring notice that `devel` has more changes, so I include all changes manually.

I know is a big intrusion on the code but really want to make a little contribution to the project.

Hope you like it, and even more, hope I haven't break anything.

Greets from Colombia.

### CODE REVIEW

**Comment by sabueso** [comment]
Hi @ma0c 

Thanks for this big work ;) Let me some days to check all changes and to think about how can we do it the dev branch.

Thanks again.

Cheers!

**Comment by ma0c** [comment]
Whatever you need I'll be here , btw, we have ticketator now live (with some minor modifications), and works perfect! we just add some mail and slack notifications and works more than nice. Any feedback that we notice with our users at tranquifinanzas, I will let you know to improve this awesome repo

**Comment by sabueso** [comment]
@ma0c You have some beers payed in Spain, again, great work ;)

**Comment by pasqualguerrero** [comment]
Yep! @ma0c , i've been reviewing your changes and after resolve some conflicts locally I've merged them into master :metal: great work, thanks.

**Pull request merged**
